"""Emit the paper's LaTeX tables directly from the evaluation CSVs.

Aggregation protocol (this is what the paper reports):
  1. For each trained model (identified by ``run_seed``), average each metric over
     the evaluation scenarios.
  2. Report mean +/- standard deviation of those per-seed means ACROSS seeds.

So the error bars measure variability across independently trained models, not
across scenarios within one model. Deterministic baselines (SP, CA-Global) do not
depend on the model, so their spread across seeds is zero by construction; this is
expected and is stated in the paper.

Writes paper/tables/{main,generalization,failure,ablation}.tex, which main.tex
\\input's, so no number is ever typed by hand.
"""

from __future__ import annotations

import argparse
import csv
import glob
import os
from collections import defaultdict

import numpy as np

METHOD_LABEL = {
    "sp": "SP (deployed rule)",
    "deflect_local": "Deflect-Local (no learning)",
    "ca_global": "CA-Global (centralized ref.)",
    "deflect_oracle": "Deflect-Oracle (ceiling)",
    "glider": "GLIDER (ours)",
    "glider_nomp": "GLIDER-noMP (ablation)",
}
CONSTEL_LABEL = {
    "starlink_shell1": "Starlink-like (train)",
    "kuiper_shell": "Kuiper-like",
    "telesat_polar": "Telesat-like",
    "medium": "Medium",
}


def _load(path: str) -> list[dict]:
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _finite(vals: list[float]) -> list[float]:
    return [v for v in vals if np.isfinite(v)]


def per_seed_means(rows: list[dict], metric: str) -> dict[int, float]:
    """Average `metric` over scenarios, separately for each run_seed."""
    by_seed: dict[int, list[float]] = defaultdict(list)
    for r in rows:
        try:
            v = float(r[metric])
        except (ValueError, KeyError):
            continue
        by_seed[int(r["run_seed"])].append(v)
    out = {}
    for s, vals in by_seed.items():
        f = _finite(vals)
        if f:
            out[s] = float(np.mean(f))
    return out


def mean_std(rows: list[dict], metric: str) -> tuple[float, float, int]:
    ps = per_seed_means(rows, metric)
    if not ps:
        return float("nan"), float("nan"), 0
    vals = np.array(list(ps.values()))
    return float(vals.mean()), float(vals.std()), len(vals)


def fmt(mean: float, std: float, prec: int = 3) -> str:
    if not np.isfinite(mean):
        return "---"
    if not np.isfinite(std) or std == 0.0:
        return f"${mean:.{prec}f}$"
    return f"${mean:.{prec}f} \\pm {std:.{prec}f}$"


def collect(results_dir: str, pattern: str, method: str) -> list[dict]:
    rows: list[dict] = []
    for p in sorted(glob.glob(os.path.join(results_dir, pattern))):
        rows += [r for r in _load(p) if r["method"] == method]
    return rows


def table_main(results_dir: str, out_dir: str, train_constel: str = "starlink_shell1") -> None:
    """In-distribution table on the training (mega-)constellation.

    Ordered SP < Deflect-Local < GLIDER < Deflect-Oracle < CA-Global so a reader sees
    exactly where the learned ranker lands: it must sit above the zero-learning
    Deflect-Local baseline to justify itself, and below the Deflect-Oracle ceiling.
    """
    metrics = [
        ("carried_fraction", "Carried", 3),
        ("max_utilization", "Peak util.", 2),
        ("p95_latency_ms", "p95 lat. (ms)", 1),
        ("mean_path_hops", "Hops", 2),
    ]
    # (row label, method name in CSV, glob pattern, distributed?)
    specs = [
        ("sp",             "sp",             f"main_{train_constel}_s*.csv", "yes"),
        ("deflect_local",  "deflect_local",  f"main_{train_constel}_s*.csv", "yes"),
        ("glider",         "glider",         f"main_{train_constel}_s*.csv", "yes"),
        ("deflect_oracle", "deflect_oracle", f"main_{train_constel}_s*.csv", "no"),
        ("ca_global",      "ca_global",      f"main_{train_constel}_s*.csv", "no"),
        ("glider_nomp",    "glider",         f"nomp_{train_constel}_s*.csv", "yes"),
    ]
    lines = [
        "% Auto-generated by scripts/make_tables.py. Do not edit.",
        "\\begin{tabular}{lccccc}",
        "\\toprule",
        "Method & Distr. & " + " & ".join(m[1] for m in metrics) + " \\\\",
        "\\midrule",
    ]
    for label, method, pattern, distr in specs:
        rows = collect(results_dir, pattern, method)
        if not rows:
            continue
        cells = [fmt(*mean_std(rows, m)[:2], prec=p) for m, _n, p in metrics]
        lines.append(f"{METHOD_LABEL[label]} & {distr} & " + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    _write(out_dir, "main.tex", lines)


def table_generalization(results_dir: str, out_dir: str) -> None:
    """Carried demand per constellation, showing where learning has headroom.

    Columns include the zero-learning Deflect-Local baseline and the Deflect-Oracle
    ceiling, so the reader sees the story directly: on small shells Deflect-Local
    already sits at the ceiling (no headroom), while on mega-constellations a gap
    opens that only a non-myopic policy can close.
    """
    constels = ["starlink_shell1", "kuiper_shell", "telesat_polar", "medium"]
    methods = ["sp", "deflect_local", "glider", "deflect_oracle"]
    lines = [
        "% Auto-generated by scripts/make_tables.py. Do not edit.",
        "\\begin{tabular}{l" + "c" * len(methods) + "}",
        "\\toprule",
        "Constellation & " + " & ".join(METHOD_LABEL[m].split(" (")[0] for m in methods) + " \\\\",
        "\\midrule",
    ]
    for c in constels:
        cells = []
        any_row = False
        for m in methods:
            rows = collect(results_dir, f"main_{c}_s*.csv", m)
            if rows:
                any_row = True
            cells.append(fmt(*mean_std(rows, "carried_fraction")[:2]) if rows else "---")
        if any_row:
            lines.append(f"{CONSTEL_LABEL.get(c, c)} & " + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    _write(out_dir, "generalization.tex", lines)


def table_failure(results_dir: str, out_dir: str) -> None:
    """Carried demand versus ISL failure rate."""
    methods = ["sp", "deflect_local", "glider", "deflect_oracle"]
    fracs = sorted({
        os.path.basename(p).split("_")[1]
        for p in glob.glob(os.path.join(results_dir, "failure_*_s*.csv"))
    })
    if not fracs:
        return
    lines = [
        "% Auto-generated by scripts/make_tables.py. Do not edit.",
        "\\begin{tabular}{l" + "c" * len(methods) + "}",
        "\\toprule",
        "ISL failure rate & " + " & ".join(METHOD_LABEL[m].split(" (")[0] for m in methods) + " \\\\",
        "\\midrule",
    ]
    for f in fracs:
        cells = []
        for m in methods:
            rows = collect(results_dir, f"failure_{f}_s*.csv", m)
            cells.append(fmt(*mean_std(rows, "carried_fraction")[:2]) if rows else "---")
        lines.append(f"{float(f)*100:.0f}\\% & " + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    _write(out_dir, "failure.tex", lines)


def _write(out_dir: str, name: str, lines: list[str]) -> None:
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, name)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"[glider] wrote {path}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="results")
    ap.add_argument("--out", default="../paper/tables")
    args = ap.parse_args()
    table_main(args.results, args.out)
    table_generalization(args.results, args.out)
    table_failure(args.results, args.out)


if __name__ == "__main__":
    main()
